#!/bin/bash

target=/mnt/d/Backups
[ ! -z $BACKUP_DIR ] && target=$BACKUP_DIR

if [ ! -d $target ]; then
    echo "Set \$BACKUP_DIR first."
elif [ -z $1 ]; then
    echo "Create a backup for a file."
else
    short=$(basename $1)
    dir=$(dirname "$(realpath $1)")
    ver=$(date "+%Y%m%d%H%M%S")
    target=$target/$dir
    [ ! -d "$target" ] && mkdir -p "$target"
    cp -r "$dir/$short" "$target/$short.$ver" && echo "Backup '$short.$ver' created at '$target'."
fi

