#!/bin/bash

color_source=$(which color) # /9ecbf/bin/color

if [ -f "$color_source" ]; then
    source $color_source
    echo -e "\n$(reset)Hi $(color 10)$(whoami)$(reset)! $(color 14)Have a nice day!$(reset)"
else
    echo -e "\nHi $(whoami)! Have a nice day!"
fi
