#!/bin/bash

# It's just to clear the screen and to send a greet in a... colorful way.

color() {
    # black=0
    # red=1
    # green=2
    # yellow=3
    # blue=4
    # magenta=5
    # cyan=6
    # light_white=7
    # gray=8
    # light_red=9
    # light_green=10
    # light_yellow=11
    # light_blue=12
    # light_magenta=13
    # light_cyan=14
    # white=15
    tput setaf $1
}

reset() {
    tput sgr0
}

clear && echo -e "\n$(reset)Hi $(color 10)$(whoami)$(reset)! $(color 14)Have a nice day!$(reset)"
