#!/bin/bash

wsl_distro_name=$1
[ -z "$wsl_distro_name" ] && echo "You must specify a distribution." && exit 1
echo "Switching to distribution '$wsl_distro_name'..."
/mnt/c/Windows/System32/wsl.exe -d $wsl_distro_name --cd ~
